# Generated by Django 3.0 on 2019-12-17 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del libro', max_length=30)),
                ('autor', models.CharField(help_text='Nombre del autor', max_length=20)),
                ('editorial', models.CharField(help_text='Editorial del libro', max_length=20)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.Persona')),
            ],
        ),
    ]
