# Generated by Django 3.0 on 2019-12-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(help_text='Introduzca nombre de usuario', max_length=30)),
                ('autor', models.CharField(help_text='Nombre del autor', max_length=20)),
                ('apellidos', models.CharField(help_text='Introduzca sus apellidos', max_length=70)),
                ('telefono', models.CharField(help_text='9611234567', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.TextField()),
            ],
        ),
    ]
