# Generated by Django 3.0 on 2019-12-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(choices=[('NO', 'Novela'), ('CI', 'Ciencia'), ('RO', 'Romance'), ('CU', 'Cuentos'), ('PO', 'Poesia'), ('RE', 'Relato')], max_length=2)),
                ('autor', models.CharField(blank=True, max_length=20, null=True)),
                ('editorial', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
