# Generated by Django 3.0 on 2019-12-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20191217_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('NO', 'Novela'), ('CF', 'Ciencia Ficcion'), ('FA', 'Fantasia'), ('RO', 'Romance'), ('CU', 'Cuentos'), ('PO', 'Poesia'), ('RE', 'Relato')], max_length=2),
        ),
    ]
